<?php

/**
 * @file
 * Site Notice module hooks and theme definitions.
 */

/**
 * Implements hook_theme().
 */
function site_notice_theme($existing, $type, $theme, $path) {
  return [
    'site_notice' => [
      'render element' => 'elements',
      'template' => 'site-notice',
      'variables' => [
        'message' => NULL,
        'link' => NULL,
        'background' => 'is-default',
        'closable' => TRUE,
      ],
    ],
  ];
}
