name: PHPStan (PR to main)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-interaction --prefer-dist --ansi"
          dependency-versions: "locked"

      - name: PHPStan analyse
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=1G

